### DISCUSSION TITLE
Github代码区域的重影问题，我用了很多方式排除似乎都不能恢复正常。

### DISCUSSION THREAD

**Discussion by Xia0xia0Xia0** [F9y4ng/GreasyFork-Scripts#266] [问答专区(Question / Answer)] [answered]
安装配置好渲染参数以后，我打开github的代码查看，发现是这样的呈现，默认有很多重影，选取以后重影更加明显。

![1](https://github.com/F9y4ng/GreasyFork-Scripts/assets/101876873/e888bd68-9364-4f38-84fd-fb1c9388c045)

于是我在排除元素的部分添加了`,textarea`，我发现，默认查看时重影似乎没了，但是选取时依然存在重影问题，于是我蒙了，求助！

![2](https://github.com/F9y4ng/GreasyFork-Scripts/assets/101876873/c7484818-d1bd-4585-b193-c2b3aa7c1c48)

**Comment by F9y4ng** [comment, marked as answer]
## 原因
你遇到的这个问题是由于以下这条Github默认的CSS所造成的：

```css
.react-blob-print-hide {
    font-family: ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,"Liberation Mono",monospace !important;
}
```

它将字体样式的权重提升了，所以会导致脚本渲染的字体被覆盖掉，从而造成选取时背景文字与显示文字字体不相符，从而被选取。

默认状态下看不到是因为Github默认的样式将textarea的字体定义为`transparent`，但应用了字体阴影时字体就会凸显出来。

## 处理
从根本上解决这个问题需要双击**排除渲染的HTML标签**右边的🔔进入自定义等宽字体工具，并开启自定义等宽字体即可，不需要额外排除渲染元素。
